---
- name: Install Calibre
  become: true
  tags: install
  block:

    - name: Add calibre group
      ansible.builtin.group:
        name: calibre
        state: present

    - name: Add calibre user
      ansible.builtin.user:
        name: calibre
        group: calibre

    - name: Create calibre app directory
      ansible.builtin.file:
        path: /home/calibre/app
        state: directory
        mode: "770"
        owner: calibre
        group: calibre

    - name: Create calibre web directory
      ansible.builtin.file:
        path: /home/calibre/web
        state: directory
        mode: "770"
        owner: calibre
        group: calibre

    - name: Create calibre books directory
      ansible.builtin.file:
        path: /home/calibre/library
        state: directory
        mode: "770"
        owner: calibre
        group: calibre

    - name: Instantiate passwd database
      getent:
        database: passwd

    - name: Create calibre container
      community.docker.docker_container:
        name: calibre
        image: lscr.io/linuxserver/calibre:latest
        pull: true
        restart_policy: unless-stopped
        volumes:
          - /home/calibre/app:/config
          - /home/calibre/library:/library
        networks:
          - name: proxy_net
        env:
          TZ: Asia/Bangkok
          PUID: "{{ getent_passwd['calibre'].1 }}"
          PGID: "{{ getent_passwd['calibre'].2 }}"

    - name: Create calibre-web container
      community.docker.docker_container:
        name: calibre-web
        image: lscr.io/linuxserver/calibre-web:latest
        pull: true
        restart_policy: unless-stopped
        volumes:
          - /home/calibre/web:/config
          - /home/calibre/library:/library
        networks:
          - name: proxy_net
        env:
          TZ: Asia/Bangkok
          PUID: "{{ getent_passwd['calibre'].1 }}"
          PGID: "{{ getent_passwd['calibre'].2 }}"
          DOCKER_MODS: linuxserver/mods:universal-calibre
