---
- name: Install Calibre
  become: true
  tags: install
  block:

    - name: Add calibre group
      ansible.builtin.group:
        name: calibre
        state: present

    - name: Add calibre user
      ansible.builtin.user:
        name: calibre
        group: calibre

    - name: Create calibre config directory
      ansible.builtin.file:
        path: /home/calibre/config
        state: directory
        mode: "770"
        owner: calibre
        group: calibre

    - name: Create calibre books directory
      ansible.builtin.file:
        path: /home/calibre/books
        state: directory
        mode: "770"
        owner: calibre
        group: calibre

    - name: Copy blank database
      ansible.builtin.copy:
        src: metadata.db
        dest: /home/calibre/books/metadata.db
        owner: calibre
        group: calibre
        force: false
        mode: u=rw,g=r,o=

    - name: Instantiate passwd database
      getent:
        database: passwd

    - name: Create calibre-web container
      community.docker.docker_container:
        name: calibre-web
        image: lscr.io/linuxserver/calibre-web:latest
        pull: true
        restart_policy: unless-stopped
        volumes:
          - /home/calibre/config:/config
          - /home/calibre/books:/books
        networks:
          - name: proxy_net
        env:
          TZ: Asia/Bangkok
          PUID: "{{ getent_passwd['calibre'].1 }}"
          PGID: "{{ getent_passwd['calibre'].2 }}"
          DOCKER_MODS: linuxserver/mods:universal-calibre
